version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
     # SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    ports:
      - "80:80"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
    ports:
      - "8891:8890"
  db:
    image: cecemel/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
      LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP: "true"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.21.1
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.2
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  sink:
    image: nginx:1.15.2
    volumes:
      - ./config/sink/sink.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    labels:
      - "logging=true"
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/contacthub/accounts"
    links:
      - db:database
    restart: always
    logging: *default-logging
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database
    restart: "no"